In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
print(df)

                 Actor                      Film  Year            Genre  \
0       Shah Rukh Khan                   Pathaan  2023           Action
1          Salman Khan           Tiger Zinda Hai  2017           Action
2           Aamir Khan                    Dangal  2016        Biography
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
4        Ranveer Singh                 Padmaavat  2018       Historical
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
6        Rajkummar Rao                     Stree  2018    Horror Comedy
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
1                    565   6.0
2                   2024   8.4
3                    431   5.6
4                    585   7.0
5                    111   8.3
6                    180   7.5
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2

In [4]:
type(df['Actor'])

pandas.core.series.Series

In [5]:
df["Year"]

0     2023
1     2017
2     2016
3     2022
4     2018
5     2018
6     2018
7     2019
8     2019
9     2022
10    2017
11    2019
Name: Year, dtype: int64

In [6]:
df.loc[3]

Actor                   Ranbir Kapoor
Film                       Brahmastra
Year                             2022
Genre                         Fantasy
BoxOffice(INR Crore)              431
IMDb                              5.6
Name: 3, dtype: object

In [7]:
df.iloc[3]

Actor                   Ranbir Kapoor
Film                       Brahmastra
Year                             2022
Genre                         Fantasy
BoxOffice(INR Crore)              431
IMDb                              5.6
Name: 3, dtype: object

In [15]:
df.loc[0:2, ["Actor", "Year"]]   # Rows 0 to 2, selected columns

            Actor  Year
0  Shah Rukh Khan  2023
1     Salman Khan  2017
2      Aamir Khan  2016

In [16]:
df.iloc[0:2, 0:2]              # Rows and cols by index position

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [20]:
df.at[5, "Actor"]       # Fast "label"-based access

'Ayushmann Khurrana'

In [26]:
df.iat[5, 3]           # Fast "position"-based access

'Thriller'

In [30]:
df[df["IMDb"] >= 8]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [37]:
df[(df["IMDb"] >= 5) & (df['Year'] > 2020)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [39]:
df.query("Year > 2020 and Genre == 'Action'")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [42]:
rating_limit = 7
df.query("IMDb  > @rating_limit")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2