In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_cleaning_sample.csv")

print(df)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [3]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [4]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [5]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [6]:
df.dropna(axis=1) # removes column

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [7]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [8]:
df["Age"].fillna(df["Age"].mean())  # Replace with mean

# df.ffill()      # Forward fill
# df.bfill()      # Backward fill

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [9]:
# df.duplicated()

df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [17]:
# Converts all names to lowercase.
df["Name"].str.lower() 

# Checks if 'delhi' is in the city name, case-insensitive.
df["City"].str.contains("delhi", case=False) 

# Outputs a pandas Series where each element is a list of strings (the split parts).
# This is where a Python list comes into play, but the outer object is still a pandas Series.
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [18]:
type(df["Age"])

pandas.core.series.Series

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        9 non-null      int64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [31]:
# df["Age"] = df["Age"].astype("Int64")
df["Age"] = df["Age"].fillna(0).astype(int)

# df["Date"] = pd.to_datetime(df["Date"])
# df["Category"] = df["Category"].astype("category")

In [33]:
# .apply()
# .map()
# .replace()

In [38]:
df.sort_values(["Age", "City"])

      Name  Age         City Gender              Email   Join Date
1  Charlie    0        Delhi      M    charlie@example  20-07-2021
3  Charlie    0        Delhi      M    charlie@example  20-07-2021
8  Charlie    0        Delhi      M    charlie@example  20-07-2021
4    David   22       Mumbai      M  david@example.com  12-11-2019
0    Alice   25     New York      F  alice@example.com  01-05-2021
6    Alice   25     New York      F  alice@example.com  01-05-2021
7    Alice   25     New York      F  alice@example.com  01-05-2021
5      NaN   28        Delhi      F     eve@domain.com         NaN
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020

In [39]:
# If you want the index to start from 0 and be sequential, 
# you can reset it using reset_index()

df.reset_index(drop=True, inplace=True)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        9 non-null      int64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [41]:
df

      Name  Age         City Gender              Email   Join Date
0    Alice   25     New York      F  alice@example.com  01-05-2021
1  Charlie    0        Delhi      M    charlie@example  20-07-2021
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie    0        Delhi      M    charlie@example  20-07-2021
4    David   22       Mumbai      M  david@example.com  12-11-2019
5      NaN   28        Delhi      F     eve@domain.com         NaN
6    Alice   25     New York      F  alice@example.com  01-05-2021
7    Alice   25     New York      F  alice@example.com  01-05-2021
8  Charlie    0        Delhi      M    charlie@example  20-07-2021

In [42]:
df = df[["City", "Name", "Age"]]   # Reorder as desired

In [49]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [45]:
df2 = df.copy()

In [46]:
df2

          City     Name  Age
0     New York    Alice   25
1        Delhi  Charlie    0
2  Los Angeles      Bob   30
3        Delhi  Charlie    0
4       Mumbai    David   22
5        Delhi      NaN   28
6     New York    Alice   25
7     New York    Alice   25
8        Delhi  Charlie    0

In [74]:
# df["Rank"] = df["Age"].rank()                 # Default: average method
df["Rank"] = df["Age"].rank(ascending=False, method="dense")   # 1, 2, 2, 3

In [75]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021   0.0
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   1.0
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021   0.0
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   4.0
5        0  28.0        Delhi      F     eve@domain.com           0   2.0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
7    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021   0.0

In [84]:
df_no_na = df.dropna().copy()
df_no_na.drop(columns=["Rank"])
df_no_na["Rank"] = df_no_na["Age"].rank(ascending=False, method="dense")

In [85]:
df_no_na

    Name   Age         City Gender              Email   Join Date  Rank
0  Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   1.0
4  David  22.0       Mumbai      M  david@example.com  12-11-2019   3.0
6  Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
7  Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0