In [6]:
import pandas as pd

In [10]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
s.size

4

In [13]:
type(s)

pandas.core.series.Series

In [15]:
custom_index = pd.Series([10, 20, 30, 40], index=["H", "S", "R", "E"])
print(custom_index)

H    10
S    20
R    30
E    40
dtype: int64

In [35]:
# 🍱 1. Creating sample data
data = {
    "name": ["Sarthak", "Aditi", "Karan", "Riya", "Aman"],
    "age": [21, 22, 20, 23, 22],
    "marks": [85, 90, 78, 92, 88]
}

# 📊 2. Create DataFrame
df = pd.DataFrame(data)


print(df)

      name  age  marks
0  Sarthak   21     85
1    Aditi   22     90
2    Karan   20     78
3     Riya   23     92
4     Aman   22     88

In [18]:
df.shape

(5, 3)

In [19]:
df.dtypes

name     object
age       int64
marks     int64
dtype: object

In [20]:
df.describe()

             age      marks
count   5.000000   5.000000
mean   21.600000  86.600000
std     1.140175   5.458938
min    20.000000  78.000000
25%    21.000000  85.000000
50%    22.000000  88.000000
75%    22.000000  90.000000
max    23.000000  92.000000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [21]:
df["name"]

0    Sarthak
1      Aditi
2      Karan
3       Riya
4       Aman
Name: name, dtype: object

In [27]:
df["result"] = df["marks"].apply(lambda x: "Pass" if x >= 50 else "Fail")
print("\n✅ With Result Column:")
print(df)

✅ With Result Column:
      name  age  marks result
0  Sarthak   21     85   Pass
1    Aditi   22     90   Pass
2    Karan   20     78   Pass
3     Riya   23     92   Pass
4     Aman   22     88   Pass

In [28]:
#  Drop a column
df = df.drop(columns=["result"])
print("\n🧹 After Dropping 'result' Column:\n")
print(df)

🧹 After Dropping 'result' Column:

      name  age  marks
0  Sarthak   21     85
1    Aditi   22     90
2    Karan   20     78
3     Riya   23     92
4     Aman   22     88

In [30]:
pd.read_csv("data.csv")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [32]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [33]:
print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB