In [1]:
import pandas as pd

employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees, departments)

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [6]:
pd.merge(employees, departments, how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [7]:
pd.merge(employees, departments, how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [8]:
pd.merge(employees, departments, how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [12]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

concat_df = pd.concat([df1, df2])

In [19]:
concat_df["Name"]

0      Alice
1        Bob
0    Charlie
1      David
Name: Name, dtype: object

In [22]:
print(concat_df.columns)       # Check column names
print(concat_df.shape)         # See how many rows & cols

Index(['Name'], dtype='object')
(4, 1)

In [23]:
concat_df.iloc[:, 0]  # Second 'Name' column

0      Alice
1        Bob
0    Charlie
1      David
Name: Name, dtype: object

In [24]:
concat_df

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [26]:
concat_df_col_wise = pd.concat([df1, df2], axis=1)

In [27]:
concat_df_col_wise

    Name     Name
0  Alice  Charlie
1    Bob    David

In [29]:
concat_df_col_wise.iloc[:, 1]

0    Charlie
1      David
Name: Name, dtype: object

In [30]:
concat_df_col_wise["Name"]

    Name     Name
0  Alice  Charlie
1    Bob    David